os: linux

language: go

go:
  - 1.14.x

script:
  # Test
  - go test -v

  # Build
  
  - echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USER --password-stdin
  - docker build -f Dockerfile -t simonangerbauer/ex04:latest ./
  - docker tag simonangerbauer/ex04:latest simonangerbauer/ex04:$TRAVIS_COMMIT
  - docker push simonangerbauer/ex04:latest
  - docker push simonangerbauer/ex04:$TRAVIS_COMMIT
