apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  namespace: demo-environment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo
        image: simonangerbauer/ex04:latest
        ports:
        - containerPort: 8888